// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25.05.2026, 11:14:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/dmitr/Documents/Code/Hintbook/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/plugins/**/*.{js,ts,mjs}","C:/Users/dmitr/Documents/Code/Hintbook/app/composables/**/*.{js,ts,mjs}","C:/Users/dmitr/Documents/Code/Hintbook/app/utils/**/*.{js,ts,mjs}","C:/Users/dmitr/Documents/Code/Hintbook/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dmitr/Documents/Code/Hintbook/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;